wiki/blog/urls.py
from django.conf.urls import url
from django.views.decorators.cache import cache_page

from blog.views import IndexView, PostView, CommentView, RepositoryView, RepositoryDetailView, TagListView, \
    CategoryListView, AuthorPostListView, CommentDeleteView,ProductView, DocumentView, ApiTest, DocumentListView, \
    AlbumListView

urlpatterns = [
    url(r'^$',  cache_page(2592000)(IndexView.as_view())), #youzi cache 30 days
    #url(r'^document$', DocumentListView.as_view()),
    url(r'^album/(?P<pk>[0-9]+)$', AlbumListView.as_view()),
    url(r'^document/(?P<pk>[0-9]+)$', DocumentView.as_view()),
    url(r'^product/(?P<pk>[0-9]+)$', ProductView.as_view()),
    url(r'^post/(?P<pk>[0-9]+)$', PostView.as_view()),
    url(r'^comment/add/(?P<pk>[0-9]+)$', CommentView.as_view()),
    url(r'^comment/delete/(?P<pk>[0-9]+)$', CommentDeleteView.as_view()),
    url(r'^repository$', RepositoryView.as_view()),
    url(r'^repository/(?P<pk>[0-9]+)$', RepositoryDetailView.as_view()),
    url(r'^tag/(?P<slug>[\w\u4e00-\u9fa5]+)$', TagListView.as_view()),
    url(r'^category/(?P<slug>[\w\u4e00-\u9fa5]+)$', CategoryListView.as_view()),
    url(r'^author/(?P<pk>[0-9]+)$', AuthorPostListView.as_view()),
    url(r'^api/(?P<pid>[0-9]+)/(?P<mid>[0-9]+)$', ApiTest)
]

wiki/zer0Blog/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'', include('blog.admin_urls')),
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'^ueditor/', include('ueditor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wiki/blog/models.py
# -*- coding:utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.db import models
from tagging.models import Tag
from tagging.fields import TagField
from tagging.registry import register

STATUS = {
        0: u'草稿',
        1: u'发布',
        2: u'删除',
}

EDITOR = [
    u'文本类型',
    u'程序类型',
]


# 复写TagField的sava方法，让它不做任何事
class TagField_Mine(TagField):
    def _save(self, **kwargs):
        pass


# class Editor(models.Model):
#     name = models.CharField(max_length=20, primary_key=True)
#     avaliable = models.BooleanField(default=True)
#
#     def __str__(self):
#        return self.name


#用户基础信息
class User(AbstractUser):
    name = models.CharField(max_length=12)
    # editor_choice = models.ForeignKey(Editor, null=True, blank=True, default="tinyMCE")
    editor_choice = models.CharField(max_length=20, default='tinyMCE')
    avatar_path = models.ImageField(upload_to="/avatar", default="/static/image/avatar_default.jpg")
    wx_user_name = models.CharField(max_length=80, default='')

    def __str__(self):
        return self.name

#微信好友关系
class Wxfriends(models.Model):
    user_id = models.IntegerField(default=1)
    attr_id = models.CharField(max_length=100, default='')
    user_name = models.CharField(max_length=80, default='')
    nick_name = models.CharField(max_length=255, default='')
    remark_name = models.CharField(max_length=80, default='')
    province = models.CharField(max_length=20, default='')
    city = models.CharField(max_length=20, default='')
    sex = models.CharField(max_length=3, default='')
    img = models.CharField(max_length=255, default='')
    sign = models.CharField(max_length=255, default='')
    contact_flag = models.CharField(max_length=8, default='')
    sns_flag = models.CharField(max_length=8, default='')

    def __str__(self):
        return self.user_name

#微信群组
class Wxgroups(models.Model):
    room_id = models.CharField(max_length=100, default='')
    user_id = models.CharField(max_length=10, default='')
    user_name = models.CharField(max_length=80, default='')
    nick_name = models.CharField(max_length=255, default='')
    remark_name = models.CharField(max_length=80, default='')
    img = models.CharField(max_length=255, default='')

    def __str__(self):
        return self.user_name

class Catalogue(models.Model):
    name = models.CharField(max_length=20, primary_key=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=100)
    publish_time = models.DateTimeField(auto_now_add=True)  # 第一次保存时自动添加时间
    modify_time = models.DateTimeField(auto_now_add=True)  # 每次保存自动更新时间
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    content = models.TextField()
    catalogue = models.ForeignKey(Catalogue)
    tag = TagField_Mine()
    view_count = models.IntegerField(editable=False, default=0)
    status = models.SmallIntegerField(default=0, choices=STATUS.items())  # 0为草稿，1为发布，2为删除
    # editor_choice = models.ForeignKey(Editor)
    editor_choice = models.CharField(max_length=20)

    def __str__(self):
        return self.title

    def get_tags(self):
        return Tag.objects.get_for_object(self)

    def update_tags(self, tag_name):
        # 把list转为string
        tag_str = "".join(tag_name)
        Tag.objects.update_tags(self, tag_str)

    def remove_tags(self):
        Tag.objects.update_tags(self, None)

    class Meta:
        ordering = ['-modify_time']


class Comment(models.Model):
    post = models.ForeignKey(Post)
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    publish_Time = models.DateTimeField(auto_now_add=True)
    ip_address = models.GenericIPAddressField()
    content = models.TextField()
    root_id = models.IntegerField(default=0)  # 评论的最上层评论，若该评论处于最上层，则为0，
    parent_id = models.IntegerField(default=0)  # 评论的父评论，若无父评论，则为0

    def __str__(self):
        return self.content


class Carousel(models.Model):
    title = models.CharField(max_length=100)
    img = models.ImageField(upload_to="/carousel")
    post = models.ForeignKey(Post)
    create_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-create_time']


# 知识库模型
class Repository(models.Model):
    title = models.CharField(max_length=100)
    publish_time = models.DateTimeField(auto_now_add=True)  # 第一次保存时自动添加时间
    author = models.CharField(max_length=20)
    content = models.TextField()
    tag = models.ManyToManyField(Tag, blank=True, default="")  # 外键tag可为空，外键被删除时该值设定为默认值“”
    view_count = models.IntegerField(editable=False, default=0)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-publish_time']

# 文档类型模型
class Docutype(models.Model):
    name = models.CharField(max_length=100)
    publish_time = models.DateTimeField(auto_now_add=True)  # 第一次保存时自动添加时间, 后续不会更新
    modify_time = models.DateTimeField(auto_now=True)  # 每次保存自动更新时间, 后续会更新
    author = models.ForeignKey(settings.AUTH_USER_MODEL) # 保存当前用户的ID
    is_deleted = models.SmallIntegerField(default=0)  # 0为正常，1为已删除

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-modify_time']

# 产品名称模型
class Product(models.Model):
    name = models.CharField(max_length=100)
    publish_time = models.DateTimeField(auto_now_add=True)  # 第一次保存时自动添加时间, 后续不会更新
    modify_time = models.DateTimeField(auto_now=True)  # 每次保存自动更新时间, 后续会更新
    author = models.ForeignKey(settings.AUTH_USER_MODEL) # 保存当前用户的ID
    description = models.CharField(max_length=255, default='') #简要描述
    docutype = models.ForeignKey(Docutype) #文档类型
    is_deleted = models.SmallIntegerField(default=0)  # 0为正常，1为已删除
    is_public = models.SmallIntegerField(default=0)  # 0为私密，1为公开
    menu_json =  models.TextField(default='') #目录json数据

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-modify_time']

# 文档内容模型
class Content(models.Model):
    product = models.ForeignKey(Product) #文档ID
    menu_id = models.IntegerField(default=1)  # 目录id
    content = models.TextField(default='') #内容
    content_type = models.SmallIntegerField(default=0)  # 0为editor编辑器, 1为markdown编辑器
    publish_time = models.DateTimeField(auto_now_add=True)  # 第一次保存时自动添加时间, 后续不会更新
    modify_time = models.DateTimeField(auto_now=True)  # 每次保存自动更新时间, 后续会更新

    def __str__(self):
        return str(self.menu_id)

    class Meta:
        ordering = ['-modify_time']

#保存多媒体 图片或视频
class Media(models.Model):
    name = models.CharField(max_length=255, default='')  #自定义名称
    origin_name = models.CharField(max_length=255, default='')  # 原名称
    create_time = models.DateTimeField(auto_now_add=True)  # 上传时间
    creator = models.ForeignKey(settings.AUTH_USER_MODEL)  # 创建人
    album_id = models.IntegerField(default=0)  # 相册集ID

    def __str__(self):
        return str(self.name)

    class Meta:
        ordering = ['-create_time']

#保存首页设置
class Youzipic(models.Model):
    pic_id =  models.ForeignKey('Media')   #外键：图片（多媒体）ID
    pic_type =  models.SmallIntegerField(default=0)  # 0为轮播图，1为置顶图
    create_time = models.DateTimeField(auto_now_add=True)  # 上传时间
    creator = models.ForeignKey(settings.AUTH_USER_MODEL)  # 创建人

    def __str__(self):
        return str(self.pic_id)

    class Meta:
        ordering = ['-create_time']

#保存成长数据
class Growth(models.Model):
    height = models.DecimalField(max_digits=5, decimal_places=2) #身高
    weight = models.DecimalField(max_digits=5, decimal_places=2) #体重
    head = models.DecimalField(max_digits=5, decimal_places=2)  # 头围
    create_time = models.DateTimeField(auto_now_add=True)  # 上传时间
    record_time = models.DateTimeField()  # 记录时间
    creator = models.ForeignKey(settings.AUTH_USER_MODEL)  # 创建人

    def __str__(self):
        return str(self.record_time)

    class Meta:
        ordering = ['-record_time']


#保存成长事件
class Events(models.Model):
    media_id = models.ForeignKey('Media')  # 外键：单个图片（多媒体）ID
    album_id = models.IntegerField(default=0)  # 相册集ID
    title = models.CharField(max_length=255, default='')  # 标题
    content = models.TextField() #文本内容
    create_time = models.DateTimeField(auto_now_add=True)  # 创建时间
    record_time = models.DateTimeField()  # 记录时间
    creator = models.ForeignKey(settings.AUTH_USER_MODEL)  # 创建人

    def __str__(self):
        return str(self.title)

    class Meta:
        ordering = ['-record_time']


#相册集
class Album(models.Model):
    title = models.CharField(max_length=255, default='')  # 标题
    cover = models.IntegerField(default=1)  # 单个图片（多媒体）ID
    creator = models.ForeignKey(settings.AUTH_USER_MODEL)  # 创建人
    create_time = models.DateTimeField(auto_now_add=True)  # 创建时间

    def __str__(self):
        return str(self.title)

    class Meta:
        ordering = ['-create_time']

register(Product)

wiki/blog/templates/blog/album.html
<!DOCTYPE html>
<HTML>
<HEAD>
    <TITLE> 柚子窝相册管理</TITLE>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="stylesheet" href="/static/waterfall/style.css" type="text/css" media="screen" />
    <style type="text/css">
    .caption {
        font-size: 20px;
        text-align: center;
        position: fixed;
        height: 70px;
        width: 100%;
        color: #ffffff;
        top:0;
        z-index: 99;


        background: rgb(105,155,200);
        background: -moz-radial-gradient(top left, ellipse cover, rgba(105,155,200,1) 0%, rgba(181,197,216,1) 57%);
         background: -webkit-gradient(radial, top left, 0px, top left, 100%, color-stop(0%,rgba(105,155,200,1)), color-stop(57%,rgba(181,197,216,1)));
         background: -webkit-radial-gradient(top left, ellipse cover, rgba(105,155,200,1) 0%,rgba(181,197,216,1) 57%);
         background: -o-radial-gradient(top left, ellipse cover, rgba(105,155,200,1) 0%,rgba(181,197,216,1) 57%);
         background: -ms-radial-gradient(top left, ellipse cover, rgba(105,155,200,1) 0%,rgba(181,197,216,1) 57%);
         background: radial-gradient(ellipse at top left, rgba(105,155,200,1) 0%,rgba(181,197,216,1) 57%);
         filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#699bc8', endColorstr='#b5c5d8',GradientType=1 );

    }

    .caption h1 {
        font-size: 36px;
        line-height: 48px;
    }
    </style>
    <script type="text/javascript" src="/static/waterfall/jquery-1.7.2.min.js"></script>
    <script type="text/javascript">
    $(document).ready(function(){
        $(".zoom").hide();

        $(".zoom").each(function(){//遍历所有对象
        var src=$(this).siblings("img").attr("src");
            $(this).attr({href:src});
        });

        $("#nav li").click(function(){
            $("#nav a").removeClass("hover");
            $(this).find("a").addClass("hover");
        });

        $("#waterfall li").mouseover(function(){
            $(this).addClass("hover");
            $(this).find(".zoom").show();
        });

        $("#waterfall li").mouseout(function(){
            $(this).removeClass("hover");
            $(this).find(".zoom").hide();
        });
    });
    </script>


</HEAD>


<body>
<div class="caption">
    <h1>{{ ablum_detail.title }}</h1>
    <p>{{ ablum_detail.creator.name }} 于 {{ ablum_detail.create_time |date:"Y-m-d H:i:s"}} 创建</p>
</div>



<div id="main" style="margin-top:90px;">

    <ul id="waterfall">
        {% for pic in album_list %}
        <li>
            <div class="img_block">
                <img src="/upload/youzi/{{ pic.name }}" />
                <a href="#" rel="lightbox[plants]" title="{{ pic.origin_name }}" class="zoom">放大</a>
                <p>{{ pic.origin_name }}</p>
          </div>
        </li>
        {% endfor %}

    </ul>

    <div class="clear"></div>

    <div style="visibility:hidden" id="loading" class="loading"><p><img src="/static/waterfall/images/loading.gif" /><img src=""/static/waterfall/images/load.gif" /></p></div>

</div>

<script type="text/javascript" src="/static/waterfall/lightbox.js"></script>
<script type="text/javascript" src="/static/waterfall/jquery.masonry.min.js"></script>
<script type="text/javascript">
$(function(){
    var $waterfall = $('#waterfall');
    $waterfall.masonry({
        columnWidth: 230
    });
});
</script>


</body>

</html>

wiki/blog/templates/blog/document_list.html
{% extends "./blog/base.html" %}

{% block title %}
    柚子窝文档查阅
{% endblock %}

{% block main %}
    <div class="row">
                hihih
    </div>
{% endblock %}

wiki/blog/templates/blog/index - 副本.html
{% extends "./blog/base.html" %}

{% block title %}
    博客
{% endblock %}

{% block main %}
    <div class="row">
        <div id="container-blog" class="col-md-8 col-lg-9">
            <!-- 左栏内容 -->
            <div>
                <!-- 轮播 -->
                {% if carousel_page_list %}
                    {% include "./blog/include/carousel.html" %}
                {% endif %}

                <!-- 首页文章列表 -->
                {% if objects.object_list %}
                    {% for post in objects.object_list %}
                        <div class="home-post well clearfix">
                            <div class="post-title underline clearfix">
                                <a href="/category/{{ post.catalogue.name }}">
                                    <div class="pre-cat">
                                        <div class="pre-catinner btn">
                                            {{ post.catalogue.name }}
                                        </div>
                                        <div class="pre-catarrow">
                                        </div>
                                    </div>
                                </a>

                                <h1>
                                    <a href="/post/{{ post.id }}">{{ post.title }}</a>
                                </h1>

                                <div class="post-info">
            <span>
                <span class="glyphicon glyphicon-calendar"></span>
                {{ post.publish_time | date:"Y年m月d日 H:i" }}
            </span>
            <span>
                <span class="glyphicon glyphicon-comment"></span>
                {{ post.comment_set.all | length }}
            </span>
            <span>
                <span class="glyphicon glyphicon-eye-open"></span>
                {{ post.view_count }}
            </span>
            <span>
                <span class="glyphicon glyphicon-user"></span>
                {{ post.author.name }}
            </span>

                                    <div class="post-tags">

                                        {% for tag in post.get_tags %}
                                            <a href="/tag/{{ tag.name }}"
                                               class="{% if forloop.counter0 %}hidden-xs{% endif %} ">
                                                <span class="label label-blog-{{ forloop.counter }} btn">{{ tag.name }}</span>
                                            </a>
                                        {% endfor %}
                                        <a class="visible-xs-inline-block">
                                            <span class="label label-blog-2 btn ">...</span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div class="post-content">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <p>
                                            {% autoescape off %}
                                            {{ post.content|striptags|slice:"200"}}
                                            {% endautoescape %}
                                            {% if post.content|length > 200 %}
                                                ...
                                            {% endif %}
                                        </p>
                                        <a type="button" class="btn btn-blog pull-right hidden-xs"
                                           href="/post/{{ post.id }}">阅读全文</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}

                <!-- 分页 -->
                {% if objects %}
                    {% include "./blog/include/pagination.html" %}
                {% endif %}

            </div>
        </div>
        <div class="marginTop10 col-md-4 col-lg-3 hidden-xs">
            {% include "./blog/include/year_write_posts.html" %}
            {% include "./blog/include/hot_posts.html" %}
            {% include "./blog/include/friendly_link.html" %}
        </div>
    </div>
{% endblock %}

wiki/blog/templates/blog/post_detail.html
{% extends "./blog/base.html" %}
{% block title %}{{ post.title }}{% endblock %}

{% ifequal post.editor_choice 'MarkDown' %}
    {% block css %}
        <link href="/static/editor.md/css/editormd.preview.min.css" rel="stylesheet" type="text/css"/>

        <link href="/static/jquery-emojiarea/jquery.emojiarea.css" rel="stylesheet" type="text/css"/>
    {% endblock %}
{% endifequal %}

{% block js %}
    {% ifequal post.editor_choice 'MarkDown' %}
        <script src="/static/editor.md/editormd.min.js" type="text/javascript"></script>
        <script src="/static/editor.md/lib/marked.min.js" type="text/javascript"></script>
        <script src="/static/editor.md/lib/prettify.min.js" type="text/javascript"></script>
        <script src="/static/editor.md/lib/raphael.min.js" type="text/javascript"></script>
        <script src="/static/editor.md/lib/underscore.min.js" type="text/javascript"></script>
        <script src="/static/editor.md/lib/sequence-diagram.min.js" type="text/javascript"></script>
        <script src="/static/editor.md/lib/flowchart.min.js" type="text/javascript"></script>
        <script src="/static/editor.md/lib/jquery.flowchart.min.js" type="text/javascript"></script>
    {% endifequal %}
    <script src="/static/jquery-emojiarea/jquery.emojiarea.js" type="text/javascript"></script>
    <script src="/static/jquery-emojiarea/packs/basic/emojis.js"></script>

    <script src="/static/js/post-detail.js" type="text/javascript"></script>

    <script type="text/javascript">
        $(function () {

            {% ifequal post.editor_choice 'MarkDown' %}
                var markDownEditor = editormd.markdownToHTML("article_content_view", {
                    htmlDecode: "style, script, iframe",
                    emoji: true,
                    taskList: true,
                    flowChart: true,
                    sequenceDiagram: true,
                });
            {% endifequal %}

            $('#comment_content').emojiarea({
                wysiwyg: false,
                button: '.emoji-button',
            });

        })
    </script>
{% endblock %}

{% block main %}

    <div class="row">
        <div id="container-blog" class="col-md-8 col-lg-9">
            <!-- 左栏内容 -->
            <div class="well" id="post">
                <div>
                    <h3>{{ post.title }}</h3>
                </div>
                <div>
                    {% for tag in post.get_tags %}
                        <a href="/tags/{{ tag.name }}">
                            <span class="label label-blog-{{ forloop.counter }} btn">{{ tag.name }}</span>
                        </a>
                    {% endfor %}
                </div>
                <div class="post-info">
                <span>
                    <span class="glyphicon glyphicon-calendar"></span>
                    {{ post.publish_time|date:"Y-m-d" }}
                </span>
                <span>
                    <span class="glyphicon glyphicon-comment"></span>
                    {{ post.comment_set.all | length }}
                </span>
                <span>
                    <span class="glyphicon glyphicon-eye-open"></span>
                    {{ post.view_count }}
                </span>
                <span>
                    <span class="glyphicon glyphicon-user"></span>
                    {{ post.author.name }}
                </span>
                </div>
                <hr>
                <div class="wrap" id="article_content_view" style="background-color: transparent">
                    {% ifequal post.editor_choice 'tinyMCE' %}
                        {% autoescape off %}
                            {{ post.content }}
                        {% endautoescape %}
                    {% endifequal %}

                    {% ifequal post.editor_choice 'MarkDown' %}
                        <textarea name="content" style="display:none;">
{{ post.content }}
                         </textarea>
                    {% endifequal %}
                </div>
            </div>

            <div class="well blog-comment">
                <div class="blog-comment-edit clearfix">
                    <form action="/comment/add/{{ post.id }}" id="blog-comment-form" method="post" role="form">
                        {% csrf_token %}
                        <div class="comment-text">
                            <textarea maxlength="200" placeholder="写下你的评论，限200字!" name="comment" id="comment_content"></textarea>
                            <div>
                                <input type="submit" name="commit" value="发 表" class="btn btn-info" data-disable-with="提交中...">
                                <div class="emoji-div"><a href="javascript:void(0)" class="emoji-button"><img class="emoji" width="20" height="20" src="/static/jquery-emojiarea/packs/basic/emojis/blush.png"></a></div>
                                <span class="warning" style="display: none"><i class="glyphicon glyphicon-info-sign"></i><span class="warning-text"></span></span>
                            </div>
                        </div>
                    </form>
                </div>
                <ul>
                    {% for root_comment, child_comment_list in comment_list.items %}
                        <li id="comment-{{ root_comment.id }}">
                            <div class="blog-comment-content">
                                <div class="root-comment">
                                    <div class="avatar_top">
                                        <div class="avatar"><img src="{{ root_comment.author.avatar_path }}"></div>
                                        <h4 style="color: #428bca;margin-bottom: 0px">{{ root_comment.author.name }}</h4>
                                        <p style="font-size: 10px;margin-top: 2px">{{ root_comment.publish_Time | date:"Y年m月d日 H:i" }}</p>
                                    </div>
                                    <p style="color: #232323;font-size: 14px">{% autoescape off %}{{ root_comment.content }}{% endautoescape %}</p>

                                    <div class="comment-footer clearfix text-right">
                                        {% ifequal root_comment.author.id user.id  %}
                                            <a class="delete" data-id="{{ root_comment.id }}" href="javascript:void(0)">删除</a>
                                        {% endifequal %}
                                        <a class="reply" data-id="{{ root_comment.id }}"
                                           data-nickname="{{ root_comment.author.name }}"
                                           href="javascript:void(0)">回复</a>
                                    </div>
                                </div>
                                {% if child_comment_list %}
                                <div class="child-comment-list">
                                    {% for child_comment in child_comment_list  %}
                                    <div class="child-comment" id="comment-{{ child_comment.id }}">
                                        <p>
                                            <a class="blue-link" href="#">{{ child_comment.author.name }}</a>：{% autoescape off %}{{ child_comment.content }}{% endautoescape %}
                                        </p>

                                        <div class="child-comment-footer text-right clearfix">
                                            {% ifequal child_comment.author.id user.id  %}
                                                <a data-id="{{ child_comment.id }}" class="delete" href="javascript:void(0)">删除</a>
                                            {% endifequal %}
                                            <a data-parent-id="{{ child_comment.id }}" data-root-id="{{ root_comment.id }}" data-nickname="{{ child_comment.author.name }}" class="child_reply"
                                               href="javascript:void(0)">回复</a>
                                            <span class="reply-time pull-left">
                                                {{ child_comment.publish_Time | date:"Y年m月d日 H:i" }}
                                            </span>
                                        </div>
                                    </div>
                                    {% endfor %}
                                    <form action="/comment/add/{{ post.id }}" class="child-comment-form" method="post" role="form" style="display: none">
                                        {% csrf_token %}
                                        <input type="hidden" name="root_id" value="">
                                        <input type="hidden" name="parent_id" value="">
                                        <div class="child-comment-text">
                                            <textarea maxlength="200" placeholder="写下你的评论，限200字!" name="comment"></textarea>
                                            <div>
                                                <input type="submit" name="commit" value="发 表" class="btn btn-info" data-disable-with="提交中...">
                                                <span class="warning" style="display: none"><i class="glyphicon glyphicon-info-sign"></i><span class="warning-text"></span></span>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                {% else %}
                                    <div class="child-comment-list hide">
                                        <form action="/comment/add/{{ post.id }}" class="child-comment-form" method="post" role="form" style="display: none">
                                        {% csrf_token %}
                                            <input type="hidden" name="root_id" value="">
                                            <input type="hidden" name="parent_id" value="">
                                            <div class="child-comment-text">
                                                <textarea maxlength="200" placeholder="写下你的评论，限200字!" name="comment"></textarea>
                                                <div>
                                                    <input type="submit" name="commit" value="发 表" class="btn btn-info" data-disable-with="提交中...">
                                                    <span class="warning" style="display: none"><i class="glyphicon glyphicon-info-sign"></i><span class="warning-text"></span></span>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                {% endif %}
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="marginTop10 col-md-4 col-lg-3 hidden-xs">
            {% include "./blog/include/year_write_posts.html" %}
            {% include "./blog/include/hot_posts.html" %}
            {% include "./blog/include/friendly_link.html" %}
        </div>
    </div>

{% endblock %}

wiki/blog/templates/blog/repository.html
{% extends "./blog/base.html" %}

{% block title %}
知识库
{% endblock %}

{%block main%}
<div class="row">
    <div id="container-blog" class="col-md-8 col-lg-9">
        <!-- 左栏内容 -->
        <div>
            <!-- 知识库文章列表 -->
            {% if objects.object_list %}
                {% for post in objects.object_list %}
                    {% include "./blog/include/repository_list.html" %}
                {% endfor %}
            {% endif %}

            <!-- 分页 -->
            {% if objects %}
                {% include "./blog/include/pagination.html" %}
            {% endif %}

        </div>
    </div>
    <div class="marginTop10 col-md-4 col-lg-3 hidden-xs">
        {% include "./blog/include/year_write_posts.html" %}
        {% include "./blog/include/hot_posts.html" %}
        {% include "./blog/include/friendly_link.html" %}
    </div>
</div>
{% endblock %}